entry1 = input("Proper noun  -  ")
entry2 = input("Noun  -  ")
entry3 = input("Body part  -  ")
entry4 = input("Past tense verb  -  ")
entry5 = input("Plural noun  -  ")
entry6 = input("Adjective  -  ")
entry7 = input("Verb  -  ")
entry8 = input("Past tense verb  -  ")
story = "{} had a {} with a little {} that always {} lots of {}. It was really quite {} that it always had to {}. The {} never {} her alone.".format(entry1,entry2,entry3,entry4,entry5,entry6,entry7,entry2,entry8)
print(story)
