entry1 = input("Noun  =  ")
entry2 = input("Place  =  ")
entry3 = input("Adjective  =  ")
entry4 = input("Body part  =  ")
entry5 = input("Feeling (past tense)  =  ")
story1 = ("The {} from {} had a really {} {} that always made the {} {}.\n").format(entry1,entry2,entry3,entry4,entry1,entry5)
entry6 = input("Adverb  =  ")
entry7 = input("Adjective  =  ")
entry8 = input("Noun  =  ")
entry9 = input("Person  =  ")
entry10 = input("Feeling  =  ")
story2 = ("It's {} {} {} made {} {} and always got in trouble.\n").format(entry6,entry7,entry8,entry9,entry10)
entry11 = input("Group  =  ")
entry12 = input("Verb (past tense)  =  ")
entry13 = input("Verb (past tense)  =  ")
entry14 = input("Object  =  ")
story3 = ("The {} got involved and {} the {} for the way that it {} the {}.\n").format(entry11,entry12,entry1,entry13,entry14)
print(story1,story2,story3)
